In [1]:
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [2]:
data=pd.read_csv('novagen_dataset.csv')
data.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,False,True,True,False,False
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,False,False,True,False,False
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,True,False,False,False,False
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,True,False,False,True,False
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,False,True,False,True,False

In [3]:
label_cols=['Diet_Type__Vegan','Diet_Type__Vegetarian','Blood_Group_AB','Blood_Group_B','Blood_Group_O']
for labels in label_cols:
    le=LabelEncoder()
    data[labels]=le.fit_transform(data[labels])

In [4]:
data.head()

,Age,BMI,Blood_Pressure,Cholesterol,Glucose_Level,Heart_Rate,Sleep_Hours,Exercise_Hours,Water_Intake,Stress_Level,...,Diet,MentalHealth,PhysicalActivity,MedicalHistory,Allergies,Diet_Type__Vegan,Diet_Type__Vegetarian,Blood_Group_AB,Blood_Group_B,Blood_Group_O
0,2.0,26.0,111.0,198.0,99.0,72.0,4.0,1.0,5.0,5.0,...,1,2,1,0,1,0,1,1,0,0
1,8.0,24.0,121.0,199.0,103.0,75.0,2.0,1.0,2.0,9.0,...,1,2,1,2,2,0,0,1,0,0
2,81.0,27.0,147.0,203.0,100.0,74.0,10.0,-0.0,5.0,1.0,...,2,0,0,1,0,1,0,0,0,0
3,25.0,21.0,150.0,199.0,102.0,70.0,7.0,3.0,3.0,3.0,...,1,2,1,2,0,1,0,0,1,0
4,24.0,26.0,146.0,202.0,99.0,76.0,10.0,2.0,5.0,1.0,...,2,0,2,0,2,0,1,0,1,0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9549 entries, 0 to 9548
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    9549 non-null   float64
 1   BMI                    9549 non-null   float64
 2   Blood_Pressure         9549 non-null   float64
 3   Cholesterol            9549 non-null   float64
 4   Glucose_Level          9549 non-null   float64
 5   Heart_Rate             9549 non-null   float64
 6   Sleep_Hours            9549 non-null   float64
 7   Exercise_Hours         9549 non-null   float64
 8   Water_Intake           9549 non-null   float64
 9   Stress_Level           9549 non-null   float64
 10  Target                 9549 non-null   int64
 11  Smoking                9549 non-null   int64
 12  Alcohol                9549 non-null   int64
 13  Diet                   9549 non-null   int64
 14  MentalHealth           9549 non-null   int64
 15  PhysicalActivity       9549 non-null   int64
 16  MedicalHistory         9549 non-null   int64
 17  Allergies              9549 non-null   int64
 18  Diet_Type__Vegan       9549 non-null   int64
 19  Diet_Type__Vegetarian  9549 non-null   int64
 20  Blood_Group_AB         9549 non-null   int64
 21  Blood_Group_B          9549 non-null   int64
 22  Blood_Group_O          9549 non-null   int64
dtypes: float64(10), int64(13)
memory usage: 1.7 MB

In [6]:
y=data['Target']
x=data.drop('Target',axis=1)

In [7]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score
base_model=DecisionTreeClassifier()
bagging=BaggingClassifier(base_model,n_estimators=201)
bagging.fit(x_train,y_train)
prediction=bagging.predict(x_test)
print(f'accuracy score is {accuracy_score(y_test,prediction)}')

accuracy score is 0.9403141361256544

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=201)
rf.fit(x_train,y_train)
prediction=rf.predict(x_test)
print(f'accuracy score is {accuracy_score(y_test,prediction)}')

accuracy score is 0.9418848167539267

In [10]:
from sklearn.ensemble import GradientBoostingClassifier
gbc=GradientBoostingClassifier(n_estimators=100,learning_rate=0.2,max_depth=7)
gbc.fit(x_train,y_train)
prediction=gbc.predict(x_test)
print(f'accuracy score is {accuracy_score(y_test,prediction)}')

accuracy score is 0.9455497382198953

In [11]:
from sklearn.ensemble import AdaBoostClassifier
Abc=AdaBoostClassifier(n_estimators=200,learning_rate=0.3)
Abc.fit(x_train,y_train)
prediction=Abc.predict(x_test)
print(f'accuracy score is {accuracy_score(y_test,prediction)}')

accuracy score is 0.8408376963350785

In [15]:
import xgboost as xgb

In [17]:
xgbc=xgb.XGBClassifier(n_estimators=200,learning_rate=0.3,max_depth=3)
xgbc.fit(x_train,y_train)
prediction=xgbc.predict(x_test)
print(f'accuracy score is {accuracy_score(y_test,prediction)}')

accuracy score is 0.9408376963350785

In [22]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
lr=LogisticRegression(max_iter=10000)
svc=SVC()
dtc=DecisionTreeClassifier(max_depth=5)
vc=VotingClassifier([('lr',lr),('svc',svc),('dtc',dtc)])
vc.fit(x_train,y_train)
prediction=vc.predict(x_test)
print(f'accuracy score is {accuracy_score(y_test,prediction)}')

accuracy score is 0.8366492146596859

In [23]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
lr=LogisticRegression(max_iter=10000)
svc=SVC()
dtc=DecisionTreeClassifier(max_depth=5)
dt2=DecisionTreeClassifier(max_depth=5)
sc=StackingClassifier([('lr',lr),('svc',svc),('dtc',dtc)],cv=5,final_estimator=dt2)
sc.fit(x_train,y_train)
prediction=sc.predict(x_test)
print(f'accuracy score is {accuracy_score(y_test,prediction)}')

accuracy score is 0.8738219895287959